version: "3.3"
services:
  postgres:
    image: postgres
    volumes:
      - ./B1__baseline.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local:
    driver: bridge

# docker exec -it e823990d9d8c /bin/bash